on: push
name: Publish CoronaVidas.net Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.coronavidas.net
          ftp-username: coronavidas
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /www
